

# SQL Queries for Data Analysis on Customer Shopping Behavior

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_spent_by_gender  from customer_behavior group by gender

--Q2. Which customers have spent above the average purchase amount and used a discount?

select customer_id,purchase_amount from customer_behavior 
where purchase_amount >(select AVG(purchase_amount) from customer_behavior) and discount_applied='yes'

--Q3. What are the top 5 products with the highest average review ratings?

select top 5 item_purchased, cast(AVG(review_rating) as decimal (10,2)) as avg_review_by_product 
from customer_behavior group by item_purchased order by avg_review_by_product desc

--Q4. How does the average purchase amount vary by shipping type (e.g., Express vs. Standard)?
select shipping_type, AVG(purchase_amount)  as avg_purchase_by_shipping
from customer_behavior where shipping_type in ('Express','Standard') group by shipping_type

--Q5. What is the distribution of customers based on their subscription status and their average spend?
select subscription_status, count(subscription_status) as total_customer,
round(AVG(cast(purchase_amount as decimal (10,2))),2) as avg_spend,sum(purchase_amount) as total_sum
from customer_behavior group by subscription_status

--Q6. Which items have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
cast((count(case when discount_applied = 'yes' then 1
end )*100.0 )/count(item_purchased) as decimal(10,2))as percentage_of_purchase
from customer_behavior group by item_purchased order by percentage_of_purchase desc

--Q7. Categorize customers into 'New', 'Returning', and 'Loyal' based on the number of previous purchases and provide the count for each category.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_behavior)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8.What are the top 3 most purchased products within each category?
select * from
(select category, item_purchased,count(customer_id) as total_count, row_number() over (partition by category order by count(customer_id) desc) as item_rank from customer_behavior group by category,item_purchased) a
where item_rank<=3